### ISSUE TITLE
Crash issue while initializing on my Miui device after 2023.9.20 update

### ISSUE THREAD

**Issue by BakaLee** [ZTMIDGO/Android-Stable-diffusion-ONNX#15]
After the 2023.9.20 update I am facing crash issue while initializing on my Redmi Note 4 mido. The previous version was working without crash.

Here is the screenshot and crash report.

![Screenshot_2023-09-23-15-56-13-719_com miui home](https://github.com/ZTMIDGO/Android-Stable-diffusion-ONNX/assets/49085424/f20326f8-43c5-4dc7-88a5-448b6666e778)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

Build fingerprint: 'xiaomi/mido/mido:7.0/NRD90M/V11.0.2.0.NCFMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 25854, tid: 25898, name: pool-1-thread-1  >>> com.example.open.diffusion <<<
signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x7f608bb7fc
    x0   0000007f60b811e8  x1   000000000000004d  x2   0000000000000300  x3   0000000000000300
    x4   0000007f3957ce80  x5   0000000000000001  x6   0000000000000001  x7   0000007f5ed6bbc0
    x8   0000000000000000  x9   0000007f60b7b000  x10  0000007f60b7b000  x11  0000007f60b7b000
    x12  0000007f60b7b000  x13  0000000000000000  x14  0000007f3957cef8  x15  0000000000000000
    x16  0000007f60b7ccf8  x17  0000007f8071ae9c  x18  0000007f7ba4c990  x19  0000007f5ed6bbc0
    x20  0000000000000008  x21  0000000000000300  x22  0000000000000300  x23  000000000000004d
    x24  0000007f17d90300  x25  000000000000006f  x26  0000000000000001  x27  0000007f5ceed4e8
    x28  0000007f60b81248  x29  0000007f5cee9f40  x30  0000007f608bd76c
    sp   0000007f5cee9ef0  pc   0000007f608bb7fc  pstate 0000000080000000

backtrace:
    #00 pc 0000000000b107fc  /data/app/com.example.open.diffusion-1/base.apk (offset 0x206000)
    #01 pc 0000000000b12768  /data/app/com.example.open.diffusion-1/base.apk (offset 0x206000)
    #02 pc 000000000064b174  /data/app/com.example.open.diffusion-1/base.apk (offset 0x206000)
    #03 pc 0000000000a16984  /data/app/com.example.open.diffusion-1/base.apk (offset 0x206000)
    #04 pc 0000000000a16060  /data/app/com.example.open.diffusion-1/base.apk (offset 0x206000)
    #05 pc 0000000000a2d690  /data/app/com.example.open.diffusion-1/base.apk (offset 0x206000)
    #06 pc 0000000000a19588  /data/app/com.example.open.diffusion-1/base.apk (offset 0x206000)
    #07 pc 0000000000a18e14  /data/app/com.example.open.diffusion-1/base.apk (offset 0x206000)
    #08 pc 0000000000a41850  /data/app/com.example.open.diffusion-1/base.apk (offset 0x206000)
    #09 pc 0000000000a41460  /data/app/com.example.open.diffusion-1/base.apk (offset 0x206000)
    #10 pc 0000000000a42970  /data/app/com.example.open.diffusion-1/base.apk (offset 0x206000)
    #11 pc 00000000003d420c  /data/app/com.example.open.diffusion-1/base.apk (offset 0x206000)
    #12 pc 00000000003d5f20  /data/app/com.example.open.diffusion-1/base.apk (offset 0x206000)
    #13 pc 00000000003a8acc  /data/app/com.example.open.diffusion-1/base.apk (offset 0x206000)
    #14 pc 000000000000d9fc  /data/app/com.example.open.diffusion-1/base.apk (offset 0xfd9000)
    #15 pc 000000000056cc04  /data/app/com.example.open.diffusion-1/oat/arm64/base.odex (offset 0x56a000)

**Comment by ZTMIDGO** [comment]
You can try uninstalling the program and reinstalling it

**Comment by BakaLee** [comment]
> You can try uninstalling the program and reinstalling it

Reinstalling the app didn't work.
It worked only when I replaced the lib folder from the previous version.

**Comment by ZTMIDGO** [comment]
It may be a problem with the onnxruntime version. I have tried to lower the version in the past few days, maybe the problem can be solved.

**Comment by BakaLee** [comment]
> It may be a problem with the onnxruntime version. I have tried to lower the version in the past few days, maybe the problem can be solved.

Yes, is working flawlessly without crash after replacing the Onnx runtime libs. Btw when are you implementing GPU acceleration?
