### ISSUE TITLE
huggingface上下载的模型放在哪里

### ISSUE THREAD

**Issue by TianRuiHe** [ZTMIDGO/Android-Stable-diffusion-ONNX#2]
你好，“下载 https://huggingface.co/TIEMING/Chilloutmix/tree/main 模型，复制模型到PathManager类中的getModelPath给出的路径”这部分，这个huggingface里有4个文件夹，每个都是模型的一部分，那么是要把哪个放在getModelPath给出的路径里呢？

**Comment by ZTMIDGO** [comment]
> 你好，“下载 https://huggingface.co/TIEMING/Chilloutmix/tree/main 模型，复制模型到PathManager类中的getModelPath给出的路径”这部分，这个huggingface里有4个文件夹，每个都是模型的一部分，那么是要把哪个放在getModelPath给出的路径里呢？

你可以在：UNet，EngTokenizer，VaeDecoder这三个类找到相关的代码，可以知道模型路径必须包含以下文件：

model/text_encoder/model.ort

model/tokenizer/merges.txt
model/tokenizer/special_tokens_map.json
model/tokenizer/tokenizer_config.json
model/tokenizer/vocab.json

model/unet/model.ort

model/vae_decoder/model.ort

你只需要把huggingface下载到的文件夹直接复制到model的文件夹下即可
