### ISSUE TITLE
如何生成APK

### ISSUE THREAD

**Issue by yx-chan131** [ZTMIDGO/Android-Stable-diffusion-ONNX#4]
你好，想根据你提供的方法把整个app生成流程跑通。我对安卓apk部分完全是小白，能请问下载了github代码，有了模型文件后，要怎么生成apk吗？谢谢！

**Comment by ZTMIDGO** [comment]
如果你直接把模型复制到了PathManager的getModelPath，可以跳过第一张图片和第二张图片的步骤，如果没有可以把模型复制到assets文件夹，然后执行第三张和第四张图片的步骤生成apk

![1](https://github.com/ZTMIDGO/Android-Stable-diffusion-ONNX/assets/50280785/7af60f4f-4388-4d45-86f3-440398c1a1cc)
![2](https://github.com/ZTMIDGO/Android-Stable-diffusion-ONNX/assets/50280785/3dc6c562-455a-40f8-8dd9-92b0d3ecdb9e)
![3](https://github.com/ZTMIDGO/Android-Stable-diffusion-ONNX/assets/50280785/95045317-d74a-4bb7-a524-d85de82bdb28)
![4](https://github.com/ZTMIDGO/Android-Stable-diffusion-ONNX/assets/50280785/679ae23d-3e9a-4d81-8eae-68b7bffd166f)
