### ISSUE TITLE
onnx int8量化方法

### ISSUE THREAD

**Issue by eadst** [ZTMIDGO/Android-Stable-diffusion-ONNX#6]
我参考了这个链接可以量化fp16的模型，但是替换model生成图像报错error。
[Accelerating Stable Diffusion Inference with ONNX Runtime](https://medium.com/microsoftazure/accelerating-stable-diffusion-inference-with-onnx-runtime-203bd7728540)

请问有stable diffusion模型onnx int8量化参考链接或者代码嘛？

**Comment by ZTMIDGO** [comment]
可以使用 https://github.com/Amblyopius/Stable-Diffusion-ONNX-FP16 转为onnx，然后下载 https://github.com/ZTMIDGO/Android-Stable-diffusion-ONNX/files/11745190/conv_sd_to_onnx.txt 替换项目里的conv_sd_to_onnx.py

**Comment by ZTMIDGO** [comment]
量化代码 https://github.com/LowinLi/stable-diffusion-streamlit/blob/main/src/stable-diffusion-streamlit/pages/model/quantization.py

**Comment by eadst** [comment]
感谢分享。我修改了[conv_sd_to_onnx.txt](https://github.com/ZTMIDGO/Android-Stable-diffusion-ONNX/files/11745190/conv_sd_to_onnx.txt)中的opset=14, [quantization.py](https://github.com/LowinLi/stable-diffusion-streamlit/blob/main/src/stable-diffusion-streamlit/pages/model/quantization.py)中的use_external_data_format=False, 可以成功运行runwayml/stable-diffusion-v1-5

**Comment by ReEnMikki** [comment]
> 可以使用 https://github.com/Amblyopius/Stable-Diffusion-ONNX-FP16 转为onnx，然后下载 https://github.com/ZTMIDGO/Android-Stable-diffusion-ONNX/files/11745190/conv_sd_to_onnx.txt 替换项目里的conv_sd_to_onnx.py

TypeError: download_from_original_stable_diffusion_ckpt() got an unexpected keyword argument 'checkpoint_path'

**Comment by ReEnMikki** [comment]
> 量化代码 https://github.com/LowinLi/stable-diffusion-streamlit/blob/main/src/stable-diffusion-streamlit/pages/model/quantization.py

Please elaborate how do I run this ? Nothing happens when I try to do it. It just loads for a second and nothing changes. This is my current files and folders:
So basically I have folder Model-fp16 which includes:
- subfolder text_encoder, which has model.onnx
- subfolder unet, which has model.onnx & weights.pb
- subfolder vae_decoder, which has model.onnx & weights.pb
- subfolder vae_encoder, which has modern.onnx

**Comment by ZTMIDGO** [comment]
<img width="715" alt="屏幕截图 2023-11-21 172058" src="https://github.com/ZTMIDGO/Android-Stable-diffusion-ONNX/assets/50280785/ab58ad4f-f899-44e7-b0f8-30925490cfb9">

You need to modify this

**Comment by czzzy** [comment]
ai.onnxruntime.OrtException: Error code - ORT_NOT_IMPLEMENTED - message: Failed to find kernel for com.microsoft.GroupNorm(1) (node:'GroupNorm_0' ep:'CPUExecutionProvider'). Kernel not found
用conv_sd_to_onnx.txt中的代码转onnx，再量化之后，在安卓虚拟机上显示算子不支持
